# Port address
server:
  port: 8083

spring:
  # Application name
  application:
    name: gateway-service
  # Gateway service setup
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/us/**

# Register on Eureka discovery service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/

# Actuator endpoints
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, metrics
