server:
  port: 80

spring:
  application: # service details
      name: @application.name@
      version: @application.version@ # value from pom.xml

  cloud:
    consul: # consul configs
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}
        prefer-ip-address: true
        health-check-path: ${server.servlet.context-path:}/actuator/health
        health-check-interval: 15s
        health-check-timeout: 90s
        health-check-critical-timeout: 3m
    
    gateway: # api gateway routes config
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api/v2/users/**
          filters:
            - StripPrefix=1 

management:
  endpoints: # actuator configs
    web:
      exposure:
        include: "*"
