spring:
  application:
    name: user-service                            # Application name

server:
  port: 8081                                      # Port address
  
eureka:
  instance:
    hostname: localhost
    port: 8080
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/       # Register on Eureka server        