spring:
  # Application name
  application:
    name: discovery-service

# Port address
server:
  port: 8061

# Eureka discovery service setup
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Don't register with Eureka
    fetch-registry: false # Don't fetch registry details
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
