spring:
  # Application name
  application:
    name: config-service

  # Cloud config service setup
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SubhankarDas/config.git
          search-paths:
            - '*-service'

# Port address
server:
  port: 8082

# Register with Eureka discovery service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/

# Use asymmetric key (RSA key pair) encryption for properties      
encrypt:
  keyStore:
    location: classpath:/encryptionkey.jks
    password: swastyapass
    alias: swastyakey
    secret: swastyasecret